name: Cypress Regression Tests

on: [push]

jobs:

  ui-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome107
    options: --user 1001  # ← THIS IS THE IMPORTANT LINE!
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v6
        with:
          install-command: yarn install
          wait-on: ${{ secrets.BASE_URL }}
          wait-on-timeout: 120
          browser: chrome
          record: true
          group: 'UI - Chrome'
          spec: cypress/integration/*
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
