name: End-to-end tests 🧪
on: [push]
jobs:
  cypress-run:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6