All the tests run successfully locally with the command npx cypress run. But the same tests fail in GitHub Actions with this error:

AssertionError: Timed out retrying after 4000ms

Appreciate your help. Please find the workflows yml file below:

name: E2e Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        env:
          DEBUG: "cypress:*"
        with:
          # start: npm start
          command: npx cypress run
          # command: npx cypress run --browser chrome --spec 'cypress/e2e/**/*.feature'
